<template>
  <div>
    <el-dialog title="选择工作空间" :visible="workspaceVisible" width="600px" custom-class="workspace-dialog" @close="$emit('close-workspace')">
      <div class="picker-path"><el-button icon="el-icon-back" circle :disabled="!workspaceParent" @click="$emit('browse', workspaceParent)"></el-button><span>{{ workspacePath }}</span><el-button type="text" icon="el-icon-folder-add" title="新建目录" @click="$emit('create-folder')"></el-button></div>
      <div class="root-switch"><button v-for="root in workspaceRoots" :key="root.path" :class="{ active: workspacePath === root.path }" @click="$emit('browse', root.path)"><i class="el-icon-folder"></i>{{ root.name }}</button></div>
      <div class="browser-list"><button v-for="item in workspaceItems" :key="item.path" class="browser-row" :class="{ selected: selectedWorkspace === item.path }" @dblclick="$emit('browse', item.path)" @click="$emit('select-workspace', item.path)"><i :class="item.isGitRepository ? 'el-icon-connection' : 'el-icon-folder'"></i><span>{{ item.name }}</span><i class="el-icon-arrow-right"></i></button><div v-if="!workspaceItems.length" class="browser-empty">此目录没有子目录</div></div>
      <div class="dialog-footer"><span class="selected-path">{{ selectedWorkspace || '双击进入目录，或选择当前目录' }}</span><el-button @click="$emit('close-workspace')">取消</el-button><el-button type="primary" icon="el-icon-check" :disabled="!selectedWorkspace" @click="$emit('confirm-workspace')">选择此目录</el-button></div>
    </el-dialog>

    <el-dialog title="设置" :visible="settingsVisible" width="540px" custom-class="settings-dialog" @close="$emit('close-settings')">
      <div class="settings-section"><div class="settings-label"><strong>模型</strong><span>选择模型，新建会话时生效。</span></div><el-select v-model="settings.model" class="settings-select"><el-option label="默认（跟随 Codex 配置）" value=""></el-option><el-option label="GPT-5.6 Sol" value="gpt-5.6-sol"></el-option><el-option label="GPT-5.6 Terra" value="gpt-5.6-terra"></el-option><el-option label="GPT-5.6 Luna" value="gpt-5.6-luna"></el-option><el-option label="GPT-5.5" value="gpt-5.5"></el-option><el-option label="GPT-5.2" value="gpt-5.2"></el-option></el-select></div>
      <div class="settings-section"><div class="settings-label"><strong>推理级别</strong><span>控制任务的思考深度，下一次发送时生效。</span></div><el-select v-model="settings.reasoningEffort" class="settings-select"><el-option label="默认（跟随 Codex 配置）" value=""></el-option><el-option label="低" value="low"></el-option><el-option label="中" value="medium"></el-option><el-option label="高" value="high"></el-option><el-option label="超高" value="xhigh"></el-option></el-select></div>
      <div class="settings-section"><div class="settings-label"><strong>工作权限</strong><span>控制 Codex 执行命令和修改文件时的授权方式。</span></div><el-select v-model="settings.approvalPolicy" class="settings-select"><el-option label="请求批准" value="on-request"></el-option><el-option label="帮我批准" value="on-failure"></el-option><el-option label="完全访问" value="never"></el-option></el-select><p class="settings-warning" v-if="settings.approvalPolicy === 'never'"><i class="el-icon-warning-outline"></i> 完全访问会允许 Codex 在工作空间中直接运行命令并修改文件，请确认你信任当前任务。</p><p class="settings-note">策略对新建会话生效，当前会话不会被中断。</p></div>
      <div class="dialog-footer"><el-button type="danger" plain icon="el-icon-switch-button" @click="$emit('logout')">退出登录</el-button><span class="dialog-footer-spacer"></span><el-button @click="$emit('close-settings')">取消</el-button><el-button type="primary" icon="el-icon-check" :loading="settingsSaving" @click="$emit('save-settings')">保存设置</el-button></div>
    </el-dialog>

    <el-dialog title="需要审批" :visible="approvalVisible" width="540px" custom-class="approval-dialog" :close-on-click-modal="false" :close-on-press-escape="false" :show-close="false"><div v-if="currentApproval" class="approval-intro"><span class="approval-icon"><i class="el-icon-warning-outline"></i></span><div><strong>Codex 请求执行操作</strong><p>请确认是否允许这次操作继续。{{ approvalRequests.length > 1 ? `还有 ${approvalRequests.length - 1} 项待处理` : '' }}</p></div></div><div v-if="currentApproval" class="approval-command"><code>{{ currentApproval.command || '未提供操作详情' }}</code></div><div v-if="currentApproval" class="dialog-footer"><el-button @click="$emit('respond-approval', { requestId: currentApproval.requestId, decision: 'decline' })">拒绝</el-button><el-button type="primary" @click="$emit('respond-approval', { requestId: currentApproval.requestId, decision: 'accept' })">允许一次</el-button><el-button type="success" @click="$emit('respond-approval', { requestId: currentApproval.requestId, decision: 'acceptForSession' })">本次会话允许</el-button></div></el-dialog>

    <div v-if="diffVisible" class="diff-modal" @click.self="$emit('close-diff')"><section class="diff-dialog"><header class="diff-dialog-header"><strong>{{ selectedFile || '文件修改' }}</strong><button class="diff-dialog-close" type="button" title="关闭 Diff" @click="$emit('close-diff')"><i class="el-icon-close"></i></button></header><div class="diff-dialog-body"><div v-if="diffLines.length" class="diff-code"><div v-for="(line, index) in diffLines" :key="line.key || `dialog-${index}-${line.text}`" class="diff-line" :class="`diff-line-${line.type}`"><button v-if="line.type === 'collapsed'" type="button" class="diff-expand-button" @click="$emit('expand-diff', line)"><i class="el-icon-more"></i><span>展开隐藏的 {{ line.hiddenCount }} 行</span></button><template v-else><span class="diff-line-marker">{{ line.marker }}</span><span class="diff-line-number">{{ line.oldLine || '' }}</span><span class="diff-line-number">{{ line.newLine || '' }}</span><span class="diff-line-content">{{ line.content }}</span></template></div></div><div v-else-if="diffLoading" class="inspector-empty"><i class="el-icon-loading"></i><span>正在加载修改...</span></div><div v-else class="inspector-empty"><i class="el-icon-document"></i><span>没有可显示的修改</span></div></div></section></div>
    <div v-if="fileVisible" class="diff-modal" @click.self="$emit('close-file')"><section class="diff-dialog file-dialog"><header class="diff-dialog-header"><strong>{{ fileContent ? fileContent.path : '文件预览' }}</strong><button class="diff-dialog-close" type="button" title="关闭文件预览" @click="$emit('close-file')"><i class="el-icon-close"></i></button></header><div class="diff-dialog-body file-dialog-body"><div v-if="filePreviewLoading" class="inspector-empty"><i class="el-icon-loading"></i><span>正在加载文件...</span></div><img v-else-if="filePreviewUrl" class="file-preview-image" :src="filePreviewUrl" alt="本地图片预览"><pre v-else-if="fileContent">{{ fileContent.content }}</pre><div v-else class="inspector-empty"><i class="el-icon-document"></i><span>没有可显示的内容</span></div></div></section></div>
  </div>
</template>

<script>
export default {
  name: 'WorkspaceDialogs',
  props: { workspaceVisible: Boolean, workspaceRoots: Array, workspaceItems: Array, workspacePath: String, workspaceParent: String, selectedWorkspace: String, settingsVisible: Boolean, settings: Object, settingsSaving: Boolean, approvalVisible: Boolean, approvalRequests: { type: Array, default: () => [] }, diffVisible: Boolean, diffLoading: Boolean, diffLines: Array, selectedFile: String, fileVisible: Boolean, filePreviewLoading: Boolean, fileContent: Object, filePreviewUrl: String },
  computed: { currentApproval () { return this.approvalRequests[0] || null } }
}
</script>
